### ISSUE TITLE
How to download the video dataset

### ISSUE THREAD

**Issue by tung-nd** [Yusufma03/CVRL#1]
Thanks for publishing your source code!
Can you give instructions on how to download the video dataset in your readme? That would be very helpful.

**Comment by Yusufma03** [comment]
Hi, please download the data from [the google drive link](https://drive.google.com/drive/folders/1r7i1PYY_Yhfhu7T8hlhi2DJtaeD6lIvp?usp=sharing) and put them under the root folder of CVRL.

**Comment by tung-nd** [comment]
Awesome. Thanks!
